### PR TITLE
add find_nodes command in erl

### PR DESCRIPTION
**Pull request by limitless083**

### CODE REVIEW

**Comment by limitless083** [comment]
@chrismoos hello, CI error `fatal error: erl_driver.h: No such file or directory` is not my fault, please review

**Comment by chrismoos** [comment]
@limitless083 This is fixed now on `master`, pull and rebase your change and it should build cleanly.

**Comment by limitless083** [comment]
@chrismoos Okay, I have passed all checks, please review.

**Comment by limitless083** [comment]
@chrismoos
Could you please tell me the version of Erlang you are using? The version of Erlang I am using is OTP 19.0. I am afraid that we are using different versions. I have run `./rebar eunit` and there were no any failures.

Here is the result on my computer.
image

Also, in Travis CI, it said I have passed 7 tests.

image

Could you show me the result you have run? Thank you!

**Comment by chrismoos** [comment]
Sorry for the crazy long delay @limitless083, merged now.

**Pull request merged**
